name: Appwrite Automation

on:
  workflow_dispatch:
    inputs:
      item_type:
        description: 'Type of item to create'
        required: true
        default: 'bucket'
        options:
          - bucket
          - collection
          - attribute
          - database
      path:
        description: 'Path to create item'
        required: true
      file_name:
        description: 'Name of file to create item'
        required: false

jobs:
  create_item:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - Dev

    env:
      APPWRITE_API_KEY: ${{ secrets.APPWRITE_API_KEY }}
      APPWRITE_BUCKET_ID: ${{ secrets.APPWRITE_BUCKET_ID }}
      APPWRITE_COLLECTION_ADMIN_USERS_ID: ${{ secrets.APPWRITE_COLLECTION_ADMIN_USERS_ID }}
      APPWRITE_COLLECTION_DEVICE_ID: ${{ secrets.APPWRITE_COLLECTION_DEVICE_ID }}
      APPWRITE_COLLECTION_FILE_UPLOAD: ${{ secrets.APPWRITE_COLLECTION_FILE_UPLOAD }}
      APPWRITE_COLLECTION_STANDARD_USERS_ID: ${{ secrets.APPWRITE_COLLECTION_STANDARD_USERS_ID }}
      APPWRITE_DB_ID: ${{ secrets.APPWRITE_DB_ID }}
      APPWRITE_ENDPOINT: ${{ secrets.APPWRITE_ENDPOINT }}
      APPWRITE_PROJECT_ID: ${{ secrets.APPWRITE_PROJECT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run creation script
        run: |
          source venv/bin/activate
          cd ${{ github.workspace }}/${{ github.event.inputs.path }}
          python ${{ github.event.inputs.file_name }} ${{ github.event.inputs.item_type }} ${{ github.event.inputs.file_name }}
